services:
  backend:
    build:
      context: ./backend
    container_name: pseudo-blockchain-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    # restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: pseudo-blockchain-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # restart: unless-stopped
